# Generated by Django 3.2.9 on 2021-11-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_grp', models.CharField(max_length=50)),
                ('day_of_week', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
