# Generated by Django 3.2.9 on 2021-12-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_didworkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didworkout',
            name='date',
            field=models.DateField(verbose_name='Workout date'),
        ),
        migrations.AlterField(
            model_name='didworkout',
            name='did_workout',
            field=models.CharField(choices=[('Y', 'Worked out'), ('N', 'Did not workout')], default='Y', max_length=1),
        ),
    ]
