# Generated by Django 3.2.9 on 2021-12-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_workout_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_food', models.CharField(max_length=50)),
                ('calories', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('meal', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
